# Generated by Django 5.2.3 on 2025-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_autor_options_alter_postagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
